import type { Metadata } from 'next';
import '../styles/globals.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/700.css';
import { AuthProvider } from '../context/AuthProvider'; // Adjust the path if needed
import SnackbarProvider from '@/app/snackbarProvider';

export const metadata: Metadata = {
  title: 'Rent OPS',
  description: 'Generated by Rent OPS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <SnackbarProvider>{children}</SnackbarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
